<?php

namespace AppBundle\Repository;

/**
 * SuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuserRepository extends \Doctrine\ORM\EntityRepository
{
}
